<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-DHEU5ST3" failures="0" tests="11" name="com.testingshastra.regression.AnnotationOfTestng" time="7.147" errors="2" timestamp="2023-10-04T14:05:46 IST" skipped="1">
  <testcase classname="com.testingshastra.regression.AnnotationOfTestng" name="m5" time="3.009">
    <error message="
Method AnnotationOfTestng.m5()[pri:0, instance:com.testingshastra.regression.AnnotationOfTestng@8462f31] should have thrown an exception of any of types [class java.lang.InterruptedException, class java.lang.RuntimeException]" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Method AnnotationOfTestng.m5()[pri:0, instance:com.testingshastra.regression.AnnotationOfTestng@8462f31] should have thrown an exception of any of types [class java.lang.InterruptedException, class java.lang.RuntimeException]
at org.testng.internal.invokers.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:81)
at org.testng.internal.invokers.TestInvoker.considerExceptions(TestInvoker.java:860)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:718)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- m5 -->
  <testcase classname="com.testingshastra.regression.AnnotationOfTestng" name="m4" time="0.018"/>
  <testcase classname="com.testingshastra.regression.AnnotationOfTestng" name="m2" time="0.003"/>
  <testcase classname="com.testingshastra.regression.AnnotationOfTestng" name="m9" time="0.022"/>
  <testcase classname="com.testingshastra.regression.AnnotationOfTestng" name="m1" time="0.025"/>
  <testcase classname="com.testingshastra.regression.AnnotationOfTestng" name="m6" time="4.040">
    <error message="Method com.testingshastra.regression.AnnotationOfTestng.m6() didn&#039;t finish within the time-out 4000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testingshastra.regression.AnnotationOfTestng.m6() didn't finish within the time-out 4000
at java.base@17.0.7/java.lang.Thread.sleep(Native Method)
at app//com.testingshastra.regression.AnnotationOfTestng.m6(AnnotationOfTestng.java:39)
at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17.0.7/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@17.0.7/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- m6 -->
  <testcase classname="com.testingshastra.regression.AnnotationOfTestng" name="m7" time="0.001"/>
  <testcase classname="com.testingshastra.regression.AnnotationOfTestng" name="m4" time="0.013"/>
  <testcase classname="com.testingshastra.regression.AnnotationOfTestng" name="m4" time="0.011"/>
  <testcase classname="com.testingshastra.regression.AnnotationOfTestng" name="m8" time="0.005"/>
  <testcase classname="com.testingshastra.regression.AnnotationOfTestng" name="m3">
    <skipped/>
  </testcase> <!-- m3 -->
</testsuite> <!-- com.testingshastra.regression.AnnotationOfTestng -->
